theme: null
title: "ミルクせんせーのブログ"
title-saffix: "Oxmilch's Blog by GitHub Pages"
css-update: 20260210
baseurl: "/blog"
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-pages-gem
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  