theme: null
title: "ミルクせんせーのブログ"
title-saffix: "Oxmilch's Blog by GitHub Pages"
css-update: 20260213
baseurl: "/blog"
timezone: "Asia/Tokyo"
plugins:
  - jekyll-pages-gem
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
